# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'YQPhotoBrowserDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # pod 'Kingfisher', '~> 4.0'
  # pod 'SnapKit', '~> 4.0.0'
  pod 'YQPhotoBrowser', :path => '../'
  # Pods for YQPhotoBrowser

end
